# -*- coding: utf-8 -*-
"""euclidean_distance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K5_Y_bqNsZYU8YzxWgAbu-zKnO_4Gu9s
"""
import math
def euclidean_distance(coord1, coord2):
    x1, y1, z1 = coord1[0], coord1[1], coord1[2]
    x2, y2, z2 = coord2[0], coord2[1], coord2[2]
    return math.sqrt((x2 - x1)**2 + (y2 - y1)**2 + (z2 - z1)**2)
